name: branch-flow

on:
  pull_request:
    branches: [ main ]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Fail on purpose
        run: exit 1

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job2"

  build:
    needs: job2
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Validate dependency result
        run: |
          echo "Build running. job2 result: ${{ needs.job2.result }}"
          if [[ "${{ needs.job2.result }}" != "success" ]]; then
            echo "Blocking build: job2 did not succeed."
            exit 1
          else
            echo "All good."
          fi


