name: Branch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello from job1
        run: echo "Hello from job1"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello from job2
        run: echo "Hello from job2"

  build:
    needs: job2
    runs-on: ubuntu-latest
    steps:
      - name: Final Build Step
        run: echo "Build completed!"
