name: branch-flow

on:
  pull_request:
    branches: [ main ]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate job1 PASS
        run: echo "✅ job1"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate FAIL
        run: exit 1

  build:
    needs: [job1, job2]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check job1 + job2 result
        run: |
          echo "job1 = ${{ needs.job1.result }}"
          echo "job2 = ${{ needs.job2.result }}"
          if [[ "${{ needs.job1.result }}" != "success" || "${{ needs.job2.result }}" != "success" ]]; then
            echo "❌ One or more jobs failed. Build fails."
            exit 1
          fi
          echo "✅ Build passed"
